### ISSUE TITLE
swift build is broken upstream?

### ISSUE THREAD

**Issue by victorhooi** [dustinlyons/nixos-config#101]
There seems to be some issue with building swift upstream:

https://github.com/NixOS/nixpkgs/issues/320900

I recently did a `nix flake update`, and now I can't run `nix run ./#build-switch`.

I'm surprised nobody else seems to be hitting this, as I thought swift is a dependency for nix-darwin?

**Comment by victorhooi** [comment]
This was fixed via https://github.com/NixOS/nixpkgs/pull/326588 - did a build-switch from nixpkgs-unstable (default for this repo), and all good.

**Comment by oleghalin** [comment]
It was fixed by referenced issue. It still fails as you can see in this comment https://github.com/NixOS/nixpkgs/issues/327836#issuecomment-2254676718
