### ISSUE TITLE
Build on aarch64

### ISSUE THREAD

**Issue by XLRINN** [dustinlyons/nixos-config#105]
Love your config, 
I am able to share my system between my intel MacBook, and NixOS but I can't get it to build on my M1, I just keep getting a permission denied error. 
Are we seeing any problems with this?

**Comment by dustinlyons** [comment]
Can you make sure the scripts inside apps/ have the executable (+x) flag? You'll get permission denied if these scripts don't have access to run.

This step: https://github.com/dustinlyons/nixos-config?tab=readme-ov-file#4-make-apps-executable

**Comment by dustinlyons** [comment]
@XLRINN were you able to add the +x flag to the scripts?

**Comment by XLRINN** [comment]
I was, I'm sorry I did not get back to you. 
I was using my own config from my own repo and forgot that step.
