### ISSUE TITLE
Add Homebrew Formulae to config

### ISSUE THREAD

**Issue by gjolund** [dustinlyons/nixos-config#108]
I tried adding homebrew formulae to the config in the same way as you added the casks but it keeps throwing errors, that is the recommended way to manage homebrew formulae in this fashion?

https://mynixos.com/nix-darwin/option/homebrew.brews

```nix
  homebrew = {
    enable = true;
    brews = pkgs.callPackage ./brews.nix {};
    casks = pkgs.callPackage ./casks.nix {};
    onActivation = {
      cleanup = "zap";
    };
}:
```

`brews.nix`

```nix
_:

[
  # Development Tools
  "stripe/stripe-cli/stripe"
]
```

**Comment by dustinlyons** [comment]
All I do is look up the formula here: https://formulae.brew.sh/cask/
and add whatever is found to this list: https://github.com/dustinlyons/nixos-config/blob/main/modules/darwin/casks.nix

In your case, `stripe-cli` is just `stripe-cli`, not `stripe/stripe-cli/stripe`.

This is all managed by `homebrew` here: https://github.com/dustinlyons/nixos-config/blob/dbe92f2d71b1e4b28e9bab2af9351322c41c2f3b/modules/darwin/home-manager.nix#L30

**Comment by austinrivas** [comment]
> All I do is look up the formula here: https://formulae.brew.sh/cask/ and add whatever is found to this list: https://github.com/dustinlyons/nixos-config/blob/main/modules/darwin/casks.nix
> 
> In your case, `stripe-cli` is just `stripe-cli`, not `stripe/stripe-cli/stripe`.
> 
> This is all managed by `homebrew` here:
> 
> https://github.com/dustinlyons/nixos-config/blob/dbe92f2d71b1e4b28e9bab2af9351322c41c2f3b/modules/darwin/home-manager.nix#L30

This works for casks, but the stripe-cli is distributed as a formulae and is not a cask.

typically it is installed via `homebrew install stripe-cli` and not `homebrew install --cask stripe-cli`.

this is why I was trying to add the `brews.nix` declaration file.

**Comment by dustinlyons** [comment]
This configuration doesn't currently support `brew` formula, only casks. This is because `brew` formula essentially does what the nix package manager does-- install packages. But `brew` is imperative, nix is declarative. 

You should search here for your packages instead:

https://search.nixos.org/packages?channel=24.05&show=stripe-cli&from=0&size=50&sort=relevance&type=packages&query=stripe

and add to `packages.nix`.

`brew` is only used for mac apps that have no place in nixpkgs, so we support casks.

**Comment by gjolund** [comment]
> This configuration doesn't currently support `brew` formula, only casks. This is because `brew` formula essentially does what the nix package manager does-- install packages. But `brew` is imperative, nix is declarative.
> 
> You should search here for your packages instead:
> 
> https://search.nixos.org/packages?channel=24.05&show=stripe-cli&from=0&size=50&sort=relevance&type=packages&query=stripe
> 
> and add to `packages.nix`.
> 
> In this configuration, `brew` is only used for macOS apps that do not belong in `nixpkgs`, so you can install casks.

ok that makes sense, thank you for the explanation
