### ISSUE TITLE
Not Able To install Home-brew Formula's

### ISSUE THREAD

**Issue by TanishBhandari286** [dustinlyons/nixos-config#109]
I would like you to guide me on how I can install home-brew formulas as if I add it to casks.nix it doesn't gets installed as your casks.nix searches only brew casks not formulas.
Please provide a solution to this or give me a way to install all those from nix-store with the file location and where to write it

**Comment by dustinlyons** [comment]
Please see my answer here:

https://github.com/dustinlyons/nixos-config/issues/108#issuecomment-2315998019
