### ISSUE TITLE
this creates duplicate `sh` entries in login items

### ISSUE THREAD

**Issue by gjolund** [dustinlyons/nixos-config#112]
After setting up this repo I noticed several duplicate entries for a `sh` login item.

They seem to be related to nix-darwin or this repo config, I am not sure which.

Disabling them causes a prompt for the nix password to show, so I imagine it accesses the keychain to unlock the nix partition?

```sh
~ ❯ ls /Library/LaunchAgents
org.gpgtools.Libmacgpg.xpc.plist  org.gpgtools.macgpg2.shutdown-gpg-agent.plist
org.gpgtools.macgpg2.fix.plist    org.gpgtools.updater.plist

~ ❯ ls /Library/LaunchDaemons
com.docker.socket.plist
com.docker.vmnetd.plist
com.nordvpn.macos.helper.plist
org.nixos.activate-system.plist
org.nixos.darwin-store.plist
org.nixos.nix-daemon.plist
org.nixos.nix-gc.plist
systems.determinate.nix-installer.nix-hook.plist
```

<img width="465" alt="Screenshot 2024-09-09 at 10 30 48 PM" src="https://github.com/user-attachments/assets/853be87f-42e4-4fad-9f6c-57bac6e69bda">

<img width="452" alt="Screenshot 2024-09-09 at 10 37 57 PM" src="https://github.com/user-attachments/assets/3d84014e-aaa2-4466-9924-2cbafc9aa0b3">

<img width="539" alt="Screenshot 2024-09-09 at 10 40 48 PM" src="https://github.com/user-attachments/assets/42cd6c50-7a86-4dad-ba68-e07b671642f7">

**Comment by gjolund** [comment]
I have identified 5 of these items as coming from nix-darwin, but there is a 6th item that is unaccounted for.

When you get a chance can you take a look at your login items and let me know how many `sh` entries you have?

https://github.com/LnL7/nix-darwin/issues/871

**Comment by dustinlyons** [comment]
I have 5.

![Screenshot 2024-09-13 at 3 51 03 PM](https://github.com/user-attachments/assets/26d7b3d6-664c-4ff8-b652-df14baaa0fde)

**Comment by gjolund** [comment]
ok great, so I have a unaccounted for 6th shell script in my launch items.

**Comment by dustinlyons** [comment]
Hi @gjolund, closing this if no further questions.
