### ISSUE TITLE
The key in age.identityPaths should be id_ed25519_agenix

### ISSUE THREAD

**Issue by mrdylanyin** [dustinlyons/nixos-config#122]
Based on my understanding, `id_ed25519` should be responsible for cloning the `nix-secrets` repository from GitHub, while `id_ed25519_agenix` is responsible for encrypting and decrypting the keys. So, in `modules/darwin/secrets.nix`

``` nix
identityPaths = [
"/Users/${user}/.ssh/id_ed25519"
];
```
Should it be `id_ed25519_agenix`, or did I misunderstand something?

**Comment by dustinlyons** [comment]
Sorry, I probably didn't do the best of documenting this. 

We rename `id_ed25519_agenix` to `id_ed25519` as part of install. The `id_ed25519` used at installation is thrown away, as it's just used to bootstrap `nix-secrets`.
