### ISSUE TITLE
Build error in x86_64-darwin for `gitstatus` dependency

### ISSUE THREAD

**Issue by rferrandop** [dustinlyons/nixos-config#129]
Hello, first I wanna say thanks for this awesome repository. I am starting with Nix and is awesome but overwhelming 😀.

**Problem**
1. Ran the command:
```bash 
nix run .#build
```
2. Failed to install one of its dependencies: `gitstatus`

I found an issue in the nixpgs main repository that apparently solves this error: https://github.com/NixOS/nixpkgs/issues/358116.

How long does it typically take for the fix to be available in my setup with this template? 
Would I need to make any changes on my end?

**Comment by dustinlyons** [comment]
You would need to make no changes, just `nix flake update`. In my experience it's a few days, as this repository uses the `unstable` branch of `nixpkgs`.
