### ISSUE TITLE
bin/build triggers error on fresh macOS install

### ISSUE THREAD

**Issue by zane** [dustinlyons/nixos-config#20]
Hi!

I tried the instructions in the `README` on a fresh install of macOS 13.5 on a 2022 M2 MacBook Air and ran into the following error:

```
% bin/build                
Requesting sudo to set homebrew tap permissions...
Starting build...
Switching to new generation...
building the system configuration...
setting up Homebrew (/opt/homebrew)...
Error: An existing /opt/homebrew/Library/Taps is in the way
```

Removing `/opt/homebrew/Library/Taps` (or even all of `/opt/homebrew`) seems to have no effect.

**Comment by dustinlyons** [comment]
Hmm, very strange. I was able to successfully switch to `nix-homebrew` on my M1 with a previous Homebrew install. This was last month; required [setting the `automigrate` option to `true`](https://github.com/dustinlyons/nixos-config/blob/main/flake.nix#L124). 

Does the directory ever get recreated? Or does removing it continue to result in the error?

**Comment by dustinlyons** [comment]
Oops, okay. I think on fresh installs it was complaining that directory wasn't there, but for now I removed this. Can you try again after cleaning your Nix cache `~/.cache/nix` and initializing one of the starter templates?

Or you can just drop the `mkdir -p` in `bin/build` if you don't want to go through the trouble.

**Comment by dustinlyons** [comment]
Okay, thanks for letting me know about the error!
