### ISSUE TITLE
chmod hack in `darwin-build` seems to be unnecessary

### ISSUE THREAD

**Issue by isker** [dustinlyons/nixos-config#22]
Hi. Thanks for maintaining this excellent repo. I am not using it directly, but it's guiding my own setup.

I ran into the problem that this is trying to handle: https://github.com/dustinlyons/nixos-config/blob/d9b4eca2a349d10670d65fe117c85c042b10b591/bin/darwin-build#L20-L25

And found this discussion here https://github.com/zhaofengli/nix-homebrew/issues/9#issuecomment-1774684583.  I followed the suggestion about tapping homebrew-bundle in nix, and it works.  This seems like a better approach than what `darwin-build` is doing, as far as my understanding of the situation goes 🌞.

So, maybe you want to do the same; this is just FYI.

**Comment by dustinlyons** [comment]
Oh wow, this is huge! Thanks for taking the time to let me know; I hated writing this hack 😂

I've updated the configuration. What an eloquent solution.

**Comment by dustinlyons** [comment]
Confirmed this works for me as well. Soooo happy I get to remove that incredibly egregious chmod 🙌
