### ISSUE TITLE
Fresh install issues

### ISSUE THREAD

**Issue by multivac61** [dustinlyons/nixos-config#26]
When calling `bin/build` I get the following error

```
~/dev via  v21.1.0 via 🐦
❯ mkdir -p nixos-config


~/dev via  v21.1.0 via 🐦
❯ cd nixos-config && nix flake init -t github:dustinlyons/nixos-config#starte
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

~/dev/nixos-config
❯ nix flake --extra-experimental-features nix-command --extra-experimental-features flakes init -t github:dustinlyons/nixos-config#starter
wrote: /Users/olafur/dev/nixos-config/bin/apply
wrote: /Users/olafur/dev/nixos-config/bin/nixos-build
wrote: /Users/olafur/dev/nixos-config/bin/darwin-build
wrote: /Users/olafur/dev/nixos-config/bin/build
wrote: /Users/olafur/dev/nixos-config/bin
wrote: /Users/olafur/dev/nixos-config/overlays/README.md
wrote: /Users/olafur/dev/nixos-config/overlays
wrote: /Users/olafur/dev/nixos-config/shared/home-manager.nix
wrote: /Users/olafur/dev/nixos-config/shared/files.nix
wrote: /Users/olafur/dev/nixos-config/shared/config/p10k.zsh
wrote: /Users/olafur/dev/nixos-config/shared/config/emacs/config.org
wrote: /Users/olafur/dev/nixos-config/shared/config/emacs/init.el
wrote: /Users/olafur/dev/nixos-config/shared/config/emacs/.gitignore
wrote: /Users/olafur/dev/nixos-config/shared/config/emacs
wrote: /Users/olafur/dev/nixos-config/shared/config
wrote: /Users/olafur/dev/nixos-config/shared/README.md
wrote: /Users/olafur/dev/nixos-config/shared/default.nix
wrote: /Users/olafur/dev/nixos-config/shared/packages.nix
wrote: /Users/olafur/dev/nixos-config/shared/cachix/default.nix
wrote: /Users/olafur/dev/nixos-config/shared/cachix
wrote: /Users/olafur/dev/nixos-config/shared
wrote: /Users/olafur/dev/nixos-config/flake.nix
wrote: /Users/olafur/dev/nixos-config/nixos/home-manager.nix
wrote: /Users/olafur/dev/nixos-config/nixos/disk-config.nix
wrote: /Users/olafur/dev/nixos-config/nixos/files.nix
wrote: /Users/olafur/dev/nixos-config/nixos/config/login-wallpaper.png
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/launcher.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/colors.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/confirm.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/message.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/powermenu.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/styles.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi/networkmenu.rasi
wrote: /Users/olafur/dev/nixos-config/nixos/config/rofi
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar/modules.ini
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar/bars.ini
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar/config.ini
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar/colors.ini
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar/user_modules.ini
wrote: /Users/olafur/dev/nixos-config/nixos/config/polybar
wrote: /Users/olafur/dev/nixos-config/nixos/config
wrote: /Users/olafur/dev/nixos-config/nixos/README.md
wrote: /Users/olafur/dev/nixos-config/nixos/default.nix
wrote: /Users/olafur/dev/nixos-config/nixos/packages.nix
wrote: /Users/olafur/dev/nixos-config/nixos
wrote: /Users/olafur/dev/nixos-config/darwin/home-manager.nix
wrote: /Users/olafur/dev/nixos-config/darwin/files.nix
wrote: /Users/olafur/dev/nixos-config/darwin/casks.nix
wrote: /Users/olafur/dev/nixos-config/darwin/README.md
wrote: /Users/olafur/dev/nixos-config/darwin/default.nix
wrote: /Users/olafur/dev/nixos-config/darwin/packages.nix
wrote: /Users/olafur/dev/nixos-config/darwin/dock/default.nix
wrote: /Users/olafur/dev/nixos-config/darwin/dock
wrote: /Users/olafur/dev/nixos-config/darwin

~/dev/nixos-config
❯ chmod +x bin/apply && bin/apply
\033[0;32mUsername: xxx
Email: myemail@xxx.com
Name: xxx\033[0m
\033[1;33mIs this correct? (Y/N): \033[0m
Y
\033[0;32mContinuing...\033[0m
\033[0;32mUser xxx information applied.\033[0m

~/dev/nixos-config took 2s
❯ sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin
Password:
mv: rename /etc/nix/nix.conf to /etc/nix/nix.conf.before-nix-darwin: No such file or directory

~/dev/nixos-config took 2s
❯ chmod +x bin/darwin-build && chmod +x bin/build && bin/build
Starting build...
warning: creating lock file '/Users/olafur/dev/nixos-config/flake.lock'
error: flake 'path:/Users/olafur/dev/nixos-config' does not provide attribute 'packages.aarch64-darwin.darwinConfigurations.Dustins-MBP.system', 'legacyPackages.aarch64-darwin.darwinConfigurations.Dustins-MBP.system' or 'darwinConfigurations.Dustins-MBP.system'
```

**Comment by multivac61** [comment]
Another issue is that username `dustin` is hardcoded inside `darwin/files.nix` and is not changes when calling `bin/apply`

**Comment by dustinlyons** [comment]
Thanks for letting me know! I think I introduced a recent regression when making changes. I'll fix this in a few hours.

**Comment by dustinlyons** [comment]
These should all be fixed now. Let me know if that's not the case.

**Comment by multivac61** [comment]
Thank you for the update Dustin!

Unfortunately I had to break the experimental flags into two

`nix flake --extra-experimental-features nix-command --extra-experimental-features flakes init -t github:dustinlyons/nixos-config#starter`

Otherwise I get the following error:

```dustinlyons-nixos-config/nixos-config on  main
❯ nix flake '--extra-experimental-features nix-command flakes' init -t github:dustinlyons/nixos-config#starter
error: unrecognised flag '--extra-experimental-features nix-command flakes'
Try 'nix --help' for more information.```

**Comment by multivac61** [comment]
I am not able to build using `./bin/build`

```
dustinlyons-nixos-config/nixos-config on  main [?]
❯ pwd
/Users/olafur/dev/dustinlyons-nixos-config/nixos-config

dustinlyons-nixos-config/nixos-config on  main [?]
❯ chmod +x bin/apply && bin/apply
Username: olafur
Email: olafur@genkiinstruments.com
Name: Ólafur Bjarki Bogason
Is this correct? (Y/N):
y
Continuing...
User olafur information applied.

dustinlyons-nixos-config/nixos-config on  main [?]
❯ [ -f /etc/nix/nix.conf ] && sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.before-nix-darwin

dustinlyons-nixos-config/nixos-config on  main [?]
❯ ls /etc/nix/
builder_ed25519              netrc                        nix.conf.before-nix-darwin@  registry.json@
builder_ed25519.pub          nix.conf.before-nix-darwi    nix.conf.before-nix-darwin2@

dustinlyons-nixos-config/nixos-config on  main [?]
❯ chmod +x bin/darwin-build && chmod +x bin/build && bin/build
Starting build...
error: getting status of '/nix/store/g6pf2fqf9pwnz0mz94k1qbp51hq30803-source/nixos-config': No such file or directory
```

**Comment by dustinlyons** [comment]
Can you try making your nixos-config a git repo, making an initial commit, then trying again?

**Comment by multivac61** [comment]
Worked like a charm! Maybe include the git step in the tutorial too 👍  Thank you again so much for this initiative, truly valuable!

Now however I am running into issues with `Alacritty`. For some reason it won't start up and the dock icon is a question mark... any thoughts?

[I filed a report and they told me it had something to do with a broken shell config..](https://github.com/alacritty/alacritty/issues/7359#event-10934255610)


![CleanShot 2023-11-12 at 16 14 30@2x](https://github.com/dustinlyons/nixos-config/assets/4436129/2193a226-f5fc-4ed5-bf44-35238d5e053d)

![CleanShot 2023-11-12 at 16 15 17@2x](https://github.com/dustinlyons/nixos-config/assets/4436129/ec32254f-1ded-46a0-b023-7e8c2cd1b288)

**Comment by dustinlyons** [comment]
Sometimes I see the ? in the dock icon before running alacritty or Emacs for the first time; then the icon is set. So that doesn't necessarily point to something broken; I think Zsh is starting, then fish is trying to start, and since fish can't be found it fails and doesn't start the fish shell.

**Comment by multivac61** [comment]
Hmmm strange. I am able to launch `alacritty` just fine from the Terminal. But nothing happens when I click the dock icon.

**Comment by multivac61** [comment]
![CleanShot 2023-11-14 at 12 22 46](https://github.com/dustinlyons/nixos-config/assets/4436129/56d7567f-24c2-4eda-80f3-751c5e1b145f)

**Comment by dustinlyons** [comment]
And if you run it from the shell there, you get the `fish` error? Or something else? 

In my dock I get alacritty, and doing the 'Show in Finder' option shows the app inside the Nix Store. But it seems not be installed there.

**Comment by dustinlyons** [comment]
Could also be some of these options: 
https://github.com/multivac61/dustinlyons-nixos-config/blob/main/shared/home-manager.nix#L10C1-L10C41

Can you try to remove and simplify these options are much as possible? You could even remove `powerlevel10k`.

**Comment by multivac61** [comment]
Hmm.. there isn't anything inside the `Applications` folder

![CleanShot 2023-11-16 at 15 32 54](https://github.com/dustinlyons/nixos-config/assets/4436129/daa76dc8-0139-4351-a1b6-4b8271476340)

**Comment by dustinlyons** [comment]
Okay, interesting. Are you able to launch alacritty from the terminal and it launches, but just the placement of the dock icon is broken? Or are there errors launching alacritty from the terminal?

**Comment by multivac61** [comment]
I am able to launch alacritty for the terminal just fine, no errors. It's just the dock that is broken.

**Comment by multivac61** [comment]
I grabbed the latest and built everything again.. I even restarted the computer just in case!

![CleanShot 2023-11-20 at 17 16 23](https://github.com/dustinlyons/nixos-config/assets/4436129/24c8b203-14d4-4ac3-8769-3a081db3046c)

![CleanShot 2023-11-20 at 17 15 54](https://github.com/dustinlyons/nixos-config/assets/4436129/099b0c97-adf9-4829-980c-88a28ac5118f)

Even tried one more time from scratch and then I got this..

![CleanShot 2023-11-20 at 17 41 29](https://github.com/dustinlyons/nixos-config/assets/4436129/42ab8a20-74b6-49ac-9bca-86e202cbc86f)

![CleanShot 2023-11-20 at 17 46 51](https://github.com/dustinlyons/nixos-config/assets/4436129/3c491b44-7566-4bd0-aa3d-eb0e5ef3999d)

**Comment by multivac61** [comment]
I am 90% sure this has something to do with how I set up `Alacritty`. If I remove the config dir I am able to run `Alacritty` from the sidebar... need to investigate further on my end. Closing issue now. 

ps thank you again for maintaining this template and continuing to work on it (love the new refactor!). I am learning a ton!

**Comment by multivac61** [comment]
I am 90% sure this has something to do with how I set up `Alacritty`. If I remove the config dir I am able to run `Alacritty` from the sidebar... need to investigate further on my end. Closing issue now. 

ps thank you again for maintaining this template and continuing to work on it (love the new refactor!). I am learning a ton!

**Comment by dustinlyons** [comment]
@multivac61 Good to hear! Let me know if you have any questions and I'm happy to try and help.

**Comment by tlindsay** [comment]
I'm not sure if it's actually related to this issue or not, but after running `bin/build`, I'm also getting `error: flake 'git+file:///my/nix/config' does not provide attribute 'packages.aarch64-darwin.default` or 'defaultPackage.aarch64-darwin'`

I see that it _did_ install `brew`, but it didn't install any brew _packages_, and I don't seem to have any nix packages installed either as far as I can tell.

It actually has kind of broken my whole machine, so any advice on how to fix OR rollback would be super appreciated 😅

**Comment by dustinlyons** [comment]
Hmmm, very strange. Can you paste your `flake.nix` here?
