### ISSUE TITLE
Networking wireless device fails to start

### ISSUE THREAD

**Issue by adamecooper** [dustinlyons/nixos-config#47]
Hi @dustinlyons,

I'm taking you up on your generous offer from https://github.com/dustinlyons/nixos-config/issues/40#issuecomment-1873475056. I created a [pared down version of your nixos-config](https://github.com/adamecooper/nixos-config/tree/master) for my own edification, and am having an issue where my WiFi device won't start after installing the flake from the Minimal ISO.

I can connect to WiFi using `wpa_supplicant` from the Minimal ISO in order to install NixOS on my machine. However, when I actually boot into the newly-installed NixOS, my WiFi network device fails to start (it times out after 1min 30s): 
```
A start job is running for /sys/subsystem/net/devices/wlp3s0 (12s / 1min 30s)
```

Once I log in, the device (wlp3s0) is missing when I run `ip a`. For reference, I am configuring nixos-hardware [here](https://github.com/adamecooper/nixos-config/blob/master/flake.nix#L60) and setting up networking [here](https://github.com/adamecooper/nixos-config/blob/master/configuration.nix#L30-L43) (I set the commented credentials before the installation).  

Do you have any idea what might be going wrong?

**Comment by dustinlyons** [comment]
Do you see anything related to wifi when looking at one of these?

journalctl -b | grep wlp3s0
journalctl -u NetworkManager

dmesg | grep wlp3s0

lsmod (look for WiFi modules loaded)

**Comment by dustinlyons** [comment]
Also, did you take a look at this and ensure it's represented in your config?

https://nixos.wiki/wiki/Wpa_supplicant

**Comment by adamecooper** [comment]
Running `dmesg | grep wifi` outputted:
```
[-1$ dmesg I grep wifi
4.4345871 iwlwifi 0000:03:00.0: enabling device (0000 -> 0002)
4.440292] iwlwiti 0000:03:00.0: Direct firmware load for 1wlwifi-8265-36. ucode failed with error -2
4.4403101 iwlwifi 0000:03:00.0: Direct firmware load for iwwifi-8265-35.ucode failed with error -2
4.440335] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-34. ucode failed with error -2
4.440353] iwlwifi 0000:03:00.0: Direct firmware load for 1wlwifi-8265-33. ucode failed with error -2
4.440370] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-32.ucode failed with error -2
4.440388] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-31.ucode failed with error -2
4.440406] iwwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-30. ucode failed with error -2
4.440424] iwwifi 0000:03:00.0: Direct firmware load for 1wlwifi-8265-29.ucode failed with error -2
4.440442] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-28.ucode failed with error -2
4.440459] iwlwifi 0000:03:00.0: Direct firmware load for iwlwiti-8265-27. ucode failed with error -2
4.440476] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-26 .ucode failed with error -2
4,440494] iwwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-25.ucode failed with error -2
4.4405111 iwwiri 0000:03:00.0: Direct firmware load for iwlwifi-8265-24. ucode failed with error -2
4.440528] 1wlwiri 0000:03:00.0: Direct firmware load for iwlwifi-8265-23.ucode failed with error -2
4.440545] iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-8265-22. ucode failed with error -2
4.440547] iwlwifi 0000:03:00.0: no suitable firmware found!
4.441118] iwlwifi 0000:03:00.0: minimum version required: iwlwifi-8265-22
4.441650] 1wlwifi 0000:03:00.0: maximum version supported: iwlwifi-8265-36
4.442226] 1wwifi 0000:03:00.0: check git: //git .kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
```
This led me to https://github.com/NixOS/nixpkgs/issues/271020#issuecomment-1832638245.

And adding `hardware.enableRedistributableFirmware = true;` to my `configuration.nix` file fixed the issue :tada: 

Thanks again!
