### ISSUE TITLE
How can I fix this homebrew error?

### ISSUE THREAD

**Issue by SolidRhino** [dustinlyons/nixos-config#63]
I get the following error when I try to build and switch my configuration:
```
Error: Your Homebrew is too outdated for `brew bundle`. Please run `brew update`!
```
But when I run `brew update` I get the following error:

```
/nix/store/qkmybdpgm0xdmm1qnxx91sx09l3f4dij-source/.git: Permission denied
```
How can I fix this?

Thank you

**Comment by multivac61** [comment]
I'm running into the same issue.

**Comment by multivac61** [comment]
[This has been fixed on the newest version of `nix-homebrew`](https://github.com/zhaofengli/nix-homebrew/pull/21). 

You can run `nix flake update --commit-lock-file` to update your configuration.

**Comment by dustinlyons** [comment]
Ahh, the beauty of Nix flakes 😉 Something broken? Just wait a few days, run `nix flake update` and all is good in the world. 

This summarizes mostly all breaks I encounter with the configuration.

**Comment by dustinlyons** [comment]
Closing given fix is now available.
