### ISSUE TITLE
How can I add stylix

### ISSUE THREAD

**Issue by SolidRhino** [dustinlyons/nixos-config#67]
I want to add [Stylix](https://danth.github.io/stylix/) with the option to generate a wallpaper dynamically ([See this option](https://danth.github.io/stylix/tricks.html#dynamic-wallpaper-generation-based-on-selected-theme)). But if I use this example:

```nix
stylix = {
  image = config.lib.stylix.pixel "base0A";
  base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-latte.yaml";
};
```
I get the following error:
```shell
error: undefined variable 'config'
    at /nix/store/lghn0x32saqcp5in1sw8jm04h2cvd4vv-source/flake.nix:90:25:
       89|  stylix = {
       90|    image = config.lib.stylix.pixel "base0A";
         |            ^
       91|    base16Scheme = "${pkgs.base16-schemes}/share/themes/catppuccin-latte.yaml";
```

How can I fix this?

**Comment by dustinlyons** [comment]
Make sure the first line of the file that looks like { pkgs, lib, ... }: etc includes `config`.

**Comment by dustinlyons** [comment]
Hi @SolidRhino, any luck with this?

**Comment by dustinlyons** [comment]
Closing, if you have future questions, please don't hesitate to reach out.
