### ISSUE TITLE
[Question] Have you considered adding a dock module to nix-darwin?

### ISSUE THREAD

**Issue by ivankovnatsky** [dustinlyons/nixos-config#70]
Hello, you have a very nice dock module. Have you considered adding it to https://github.com/LnL7/nix-darwin? Thought it might not that straightforward: https://github.com/LnL7/nix-darwin/blob/230a197063de9287128e2c68a7a4b0cd7d0b50a7/modules/system/defaults/dock.nix#L118. But still the community will definitely benefit from it. 

I was using myself pretty much imperative way: https://github.com/ivankovnatsky/nixos-config/blob/main/home/darwin.nix#L25, your module looks pretty elegant compared to that 😄

**Comment by dustinlyons** [comment]
Hi, thanks for the suggestion! It's actually not entirely my code, I found a gist online where someone else had described the dock in this way. It is very elegant.

Here it is: https://gist.github.com/antifuchs/10138c4d838a63c0a05e725ccd7bccdd

I think it is a good idea to contribute upstream, maybe I'll get some time at some point.
