### ISSUE TITLE
[nix run .#build] error: nixVersions.unstable has been removed.

### ISSUE THREAD

**Issue by x-0D** [dustinlyons/nixos-config#76]
<details>
<pre>
>nix run .#build
Running build for aarch64-darwin
Starting build...
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'darwin-system-24.05.20240502.63c3a29+darwin4.230a197'
         whose name attribute is located at /nix/store/p69bcs7ma6ijj8v9xsrg3nq3nn8ryn95-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'activationScript' of derivation 'darwin-system-24.05.20240502.63c3a29+darwin4.230a197'
         at /nix/store/a21fcz0fgrixwrcxw63xccrzjhb6xnym-source/modules/system/default.nix:95:7:
           94|
           95|       activationScript = cfg.activationScripts.script.text;
             |       ^
           96|       activationUserScript = cfg.activationScripts.userScript.text;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: nixVersions.unstable has been removed. For bleeding edge (Nix master, roughly weekly updated) use nixVersions.git, otherwise use nixVersions.latest.
</pre>
</details>

**Comment by dustinlyons** [comment]
Thanks for reporting this. I updated the flake and moved `pkgs.nixUnstable` over to `pkgs.nix`. This should be working now.
