### ISSUE TITLE
Step 5. Apply your current user info fails with "Invalid option. Exiting script."

### ISSUE THREAD

**Issue by victorhooi** [dustinlyons/nixos-config#80]
I'm trying to follow the install guide in the README on a new box.

I'm at step 5. and running the following comman:

```
foobar$ nix run .#apply
```
However, it seems to fail here:
```
Running apply for aarch64-darwin
Would you mind quickly starring my Github repo? yes/no [yes]: 
yes
Please enter your email: 
john@example.com
Please enter your name: 
John Smith
Username: foobar
Email: john@example.com
Name: John Smith
Is this correct? yes/no: 
yes
Invalid option. Exiting script.
```
However, there's no details on which part is the "invalid option".

Is it possible to find out what's going on here, or get some more verbose logging?

**Comment by dustinlyons** [comment]
This was a bug. The script was asking you for yes/no but only accepted y/n. I just patched and pushed a new change to accept yes/no in addition to other options.
