### ISSUE TITLE
Mac App Store applications fail to install - Redownload Unavailable with This Apple ID

### ISSUE THREAD

**Issue by victorhooi** [dustinlyons/nixos-config#83]
I just tried to run step 10. to apply changes to my system (finally! =) Yes!) - however, I seem to have hit an issue with the macOS-sourced apps:
```
$ nix run .#build-switch
Running build-switch for aarch64-darwin
Starting build...
Switching to new generation...
warning: unknown setting 'upgrade-nix-store-path-url'
building the system configuration...
warning: unknown setting 'upgrade-nix-store-path-url'
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
warning: unknown setting 'upgrade-nix-store-path-url'
setting up /run via /etc/synthetic.conf...
setting up Homebrew (/opt/homebrew)...
user defaults...
setting up user launchd services...
Homebrew bundle...
Installing mas
Installing docker
Installing visual-studio-code
Installing discord
Installing zoom
Installing 1password
Error: No downloads began
No downloads
Installing 1password has failed!
Installing wireguard
Error: No downloads began
No downloads
Installing wireguard has failed!
Homebrew Bundle failed! 2 Brewfile dependencies failed to install.
```

During the install, I got this popup dialog:

![CleanShot 2024-05-27 at 12 58 08@2x](https://github.com/dustinlyons/nixos-config/assets/243499/18250450-f0fd-45fc-9853-75d670aa09a1)

Do you know if this is expected? Or what's the workaround?

**Comment by dustinlyons** [comment]
This is an underlying thing with the `mas` terminal application. If you've previously downloaded an application using the Mac App Store before using `mas`, and thus it's already 'attached' to your account, you get this error. Apple doesn't want you to "redownload" it.

There may be some way to fix it, but it's `mas` related and not specific to Nix or this configuration.
