### ISSUE TITLE
Using "homebrew.onActivation.cleanup" to make Homebrew Cask installation part declarative?

### ISSUE THREAD

**Issue by victorhooi** [dustinlyons/nixos-config#84]
I just edited some packages in ~/nixos-config/modules/darwin/casks.nix, and realised that if I commented out a package, it didn't get uninstalled.

Anyway, I did some naive Googling (e.g. [this article](https://davi.sh/blog/2024/01/nix-darwin/)), and it seems the option I want is [homebrew.onActivation.cleanup](https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.onActivation.cleanup).

Does it make sense to make `homebrew.onActivation.cleanup = "uninstall"`, (or `= "zap"`) the default?

Or at least call it out in the README as a suggestion?

Also - it might be helpful to briefly mention in the README about enabling Full Disk Access around that point. WDYT?
```
==> Dispatching zap stanza
Error: Unable to remove some files. Please enable Full Disk Access for your terminal under System Settings → Privacy & Security → Full Disk Access.
Uninstalled 1 cask
Uninstalling mas... (7 files, 951.5KB)
Uninstalled 1 formula
Error: Refusing to untap homebrew/cask because it contains the following installed formulae or casks:
discord
docker
visual-studio-code
visual-studio-code@insiders
zoom
Setting up the Dock...
```

**Comment by dustinlyons** [comment]
It's a good idea to mention this and have it available to the user, but setting it as default could possibly be intrusive if the user doesn't realize it and accidentally removes an app they really need. Although the config is declarative, under the hood it will be imperative mac terminal commands that do the installing/uninstalling, sometimes undocumented things happen, break, etc.

My preference is to always leave stuff sitting around and then reset my system from time to time.

Anyway, I think we add this commented line

`# onActivation.cleanup = "uninstall";`

in the areas that need it under `templates/starter` and `templates/starter-with-secrets`. Feel free to add this there and open a PR, or I can get to it eventually.

**Comment by dustinlyons** [comment]
Merged this as part of your PR. Thanks!
