### ISSUE TITLE
Slightly ambiguous working in setup CLI

### ISSUE THREAD

**Issue by MoshePaul** [dustinlyons/nixos-config#89]
The following question pops up while following the install steps:
```
Would you mind quickly starring my Github repo? yes/no [yes]:
```
This is a bit confusing. Technically, if I want to star the repo, I should respond `n` for "no, I don't mind." I guessed that this wasn't the author's intent and chose `y` for "Yes I will star the repo," but really by answering `y` you are saying "Yes I do mind (no I will not star the repo)." I recommend changing the wording to something like 
```
Would you like to support my work by starring my GitHub repo?
```
to avoid this ambiguity.

**Comment by dustinlyons** [comment]
I appreciate you submitting this as I dislike bad grammar 😆

I've fixed it here: https://github.com/dustinlyons/nixos-config/commit/93618ec8f8332857c47d9eeb5394d110679a7e08
