### ISSUE TITLE
preserve host ssh agent

### ISSUE THREAD

**Issue by gjolund** [dustinlyons/nixos-config#97]
I created an issue on nixos-darwin and thought I would link to it here in case anyone else has this issue while basing their config off of this repo:

https://github.com/LnL7/nix-darwin/issues/979

**Comment by dustinlyons** [comment]
@gjolund Hi, as this code doesn't live in this repository, I will close this issue for now. However, I like that it's linked here so that we can reopen and track any relevant work if needed in the future.

Thanks!
