### ISSUE TITLE
Warn user to not type full path of disk

### ISSUE THREAD

**Issue by AlphaGX** [dustinlyons/nixos-config#99]
This is not so important, but as I ran into this problem myself I figured I should share this.

In the apply script (app/*/apply), it would be nice to warn the user not to type the full path of the disk (eg /dev/sda) otherwise it will mess up the sed command when replacing values.

```diff
- ... "${YELLOW}Please choose your boot disk (e.g., nvme0n1, sda): ${NC}" ... 
+ ... "${YELLOW}Please choose your boot disk (e.g., nvme0n1, sda) (do not type the full path "/dev/"): ${NC}" ... 
```

**Comment by dustinlyons** [comment]
Thanks, this is a good suggestion. I have improved the prompt in https://github.com/dustinlyons/nixos-config/commit/7d06bf749002418589ff97598d6b8fdb3404e37a.

For later reference, here is the command I ran on my Macbook at the root of the repository:
```
find . -type f -exec sh -c 'LC_ALL=C LANG=C sed -i "" -e "s/Please choose your boot disk (e.g., nvme0n1, sda):/Please enter the name of your boot disk (e.g., sda, nvme0n1). Do not include the full path (\"\\/dev\\/\\\"):/g" "$1"' _ {} \;
```
